### ISSUE TITLE
Error when server try's to enable plugin

### ISSUE THREAD

**Issue by TheWeirdolul** [ProjectG-Plugins/GeyserHub#17]
Whenever I try to start my server with this plugin I get this error

[00:36:29 ERROR]: Error occurred while enabling GeyserHub v1.2.0 (Is it up to date?)
java.lang.AssertionError: Unable to find resource: git.properties
	at dev.projectg.geyserhub.utils.FileUtils.getResource(FileUtils.java:10) ~[?:?]
	at dev.projectg.geyserhub.GeyserHubMain.onEnable(GeyserHubMain.java:40) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-68]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-68]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-68]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-68]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-68]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-68]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[00:36:29 INFO]: Disabling GeyserHub v1.2.0

**Comment by Konicai** [comment]
Hi, can you try the latest build: https://ci.projectg.dev/job/GeyserHub/job/master/ ? If you still get an error, can you upload your GeyserHub.jar here?

**Comment by TheWeirdolul** [comment]
It works! Thank you.

**Comment by Konicai** [comment]
No problem, did the error show up? Just curious if for some reason the file didn't exist or if for some reason your system is behaving differently

**Comment by TheWeirdolul** [comment]
Nope, no error with the jar you provided me.
